version: '3.8'
networks:
  app_network:
    driver: bridge

services:
  # Banco de dados MySQL (para o pedido-produto-service)
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - './tarefas_backend/.db:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=tarefas
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_network

  # Microsserviço de Pedido-Produto
  tarefas_backend:
    image: amazoncorretto:17-alpine-jdk
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - 8081:8081
    volumes:
      - './tarefas_backend:/app'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tarefas
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db
    networks:
      - app_network

  # Adminer para acessar o banco de dados
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 3312:8080
    environment:
      - ADMINER_DEFAULT=mysql
      - ADMINER_DESIGN=dracula
    depends_on:
      - db
    networks:
      - app_network
